[versions]
dependencyUpdates = "0.36.0"
detekt = "1.15.0"
dokka = "1.4.20"
kotlin = "1.4.21"
jacoco = "0.8.6"
jacocoKordamp = "0.42.1"
nexusPublish = "0.4.0"
nexusStaging = "0.22.0"

[dependencies]
detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
dependencyUpdates = { group = "com.github.ben-manes", name = "gradle-versions-plugin", version.ref = "dependencyUpdates" }
dokka-core = { group = "org.jetbrains.dokka", name = "dokka-core", version.ref = "dokka" }
dokka-plugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
jacoco = { group = "org.kordamp.gradle", name = "jacoco-gradle-plugin", version.ref = "jacocoKordamp" }
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
nexus-staging = { group = "io.codearte.gradle.nexus", name = "gradle-nexus-staging-plugin", version.ref = "nexusStaging" }
nexus-publish = { group = "de.marcphilipp.gradle", name = "nexus-publish-plugin", version.ref = "nexusPublish" }
