[versions]
changelog = "1.0.1"
dependencyUpdates = "0.36.0"
detekt = "1.15.0"
dokka = "1.4.20"
kotlin = "1.4.21"
kotlinBinaryValidator = "0.3.0"
nexusPublish = "0.4.0"
nexusStaging = "0.22.0"

[dependencies]
changelog = { group = "org.jetbrains.intellij.plugins", name = "gradle-changelog-plugin", version.ref = "changelog" }
detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
dependencyUpdates = { group = "com.github.ben-manes", name = "gradle-versions-plugin", version.ref = "dependencyUpdates" }
dokka-core = { group = "org.jetbrains.dokka", name = "dokka-core", version.ref = "dokka" }
dokka-plugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
kotlin-binaryCompabilityValidator = { group = "org.jetbrains.kotlinx", name = "binary-compatibility-validator", version.ref = "kotlinBinaryValidator" }
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
nexus-staging = { group = "io.codearte.gradle.nexus", name = "gradle-nexus-staging-plugin", version.ref = "nexusStaging" }
nexus-publish = { group = "de.marcphilipp.gradle", name = "nexus-publish-plugin", version.ref = "nexusPublish" }
