name: generate-version-tag

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage [alpha, beta, rc, final]'
        default: 'alpha'
        required: true
        type: choice
        options:
          - 'alpha'
          - 'beta'
          - 'rc'
          - 'final'
      scope:
        description: 'Scope [major, minor, patch] or empty'
        default: ''
        required: true
        type: choice
        options:
          - ''
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  generate:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/generate-version-tag.yaml@main
    with:
      machines: 'macos-latest, ubuntu-latest, windows-latest'
      stage: '${{ github.event.inputs.stage }}'
      scope: '${{ github.event.inputs.scope }}'
    secrets:
      TOKEN_GITHUB_ACTION: '${{ secrets.TOKEN_GITHUB_ACTION }}'
