name: generate-tag

on:
  workflow_dispatch:
    if: |
      github.ref == 'refs/heads/main' ||
      !contains(github.ref, 'SNAPSHOT') &&
      github.event.inputs.scope = 'mayor' ||
      github.event.inputs.scope = 'minor' ||
      github.event.inputs.scope = 'patch' ||
      github.event.inputs.scope = '' &&
      github.event.inputs.stage = 'alpha' ||
      github.event.inputs.stage = 'beta' ||
      github.event.inputs.stage = 'rc' ||
      github.event.inputs.stage = 'final'

    inputs:
      scope:
        description: 'Scope one of [mayor, minor, patch] or empty'
        default: ''
        required: false

      stage:
        description: 'Stage, one of [alpha, beta, rc, final]'
        default: 'alpha'
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ macOS-latest, windows-latest, ubuntu-latest ]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle build
        run: ./gradlew build -P"reckon.scope"="${{ github.event.inputs.scope }}" -P"reckon.stage"="${{ github.event.inputs.stage }}"

  generate-tag:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_GITHUB_ACTION }}

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set version
        id: versioning
        run: |
          ./gradlew -P"reckon.scope"="${{ github.event.inputs.scope }}" -P"reckon.stage"="${{ github.event.inputs.stage }}"
          echo "lib_version=$(cat build/versioning/version.txt)" >> $GITHUB_ENV

      - name: Patch Changelog
        run: ./gradlew patchChangelog mergeChangelog buildReadmeBadges -P"reckon.scope"="${{ github.event.inputs.scope }}" -P"reckon.stage"="${{ github.event.inputs.stage }}"

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Publish ${{ env.lib_version }}" -a

      - name: Generate Tag
        run: ./gradlew reckonTagCreate -P"reckon.scope"="${{ github.event.inputs.scope }}" -P"reckon.stage"="${{ github.event.inputs.stage }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: 'main'
          tags: true
          github_token: '${{ secrets.GITHUB_TOKEN }}'
