name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ macOS-latest, windows-latest ]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build

      - name: Tests
        run: ./gradlew check

      - name: Generate tests report
        run: ./gradlew jacocoTestReport

      - name: GPG setup
        env:
          gpgKey: ${{ secrets.gpgKey }}
        run: |
          cat <(echo -e "${{ secrets.gpgKey }}") | gpg --batch --import

      - name: Generate docs
        run: ./gradlew dokkaHtmlMultiModule

      - name: Maven publish
        if: ${{ matrix.os == 'macOS-latest' }}
        env:
          ossUser: ${{ secrets.ossUser }}
          ossToken: ${{ secrets.ossToken }}
          gpgKeyName: ${{ secrets.gpgKeyName }}
          gpgPassphrase: ${{ secrets.gpgPassphrase }}
        run: ./gradlew publishToSonatype -PisLibRelease=true -Psigning.gnupg.keyName=${{ secrets.gpgKeyName }} -Psigning.gnupg.passphrase=${{ secrets.gpgPassphrase }}

      - name: Maven publish Windows
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          ossUser: ${{ secrets.ossUser }}
          ossToken: ${{ secrets.ossToken }}
          gpgKeyName: ${{ secrets.gpgKeyName }}
          gpgPassphrase: ${{ secrets.gpgPassphrase }}
        run: ./gradlew publishMingwX64PublicationToSonatypeRepository -PisLibRelease=true -Psigning.gnupg.keyName=${{ secrets.gpgKeyName }} -Psigning.gnupg.passphrase=${{ secrets.gpgPassphrase }}

  upload_coverage:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload reports to Codecov
        uses: codecov/codecov-action@v1

  close_repository:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Close Maven repository
        env:
          ossUser: ${{ secrets.ossUser }}
          ossToken: ${{ secrets.ossToken }}
        run: ./gradlew closeRepository

  deploy_docs:
    runs-on: ubuntu-latest

    needs:
      - build
      - close_repository

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy docs to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/dokka
          CLEAN: false
