name: Main

on:
  push:
    branches:
      - main

env:
  ossUser: ${{ secrets.ossUser }}
  ossToken: ${{ secrets.ossToken }}
  gpgKeyName: ${{ secrets.gpgKeyName }}
  gpgPassphrase: ${{ secrets.gpgPassphrase }}
  ossStagingProfileId: ${{ secrets.ossStagingProfileId }}

jobs:
  build_and_release:
    strategy:
      matrix:
        os: [ macOS-latest, windows-latest, ubuntu-latest ]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle build
        run: ./gradlew build

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.gpgKey }}
          passphrase: ${{ secrets.gpgPassphrase }}

      - name: Publish
        run: ./gradlew publishToSonatype -P"isLibRelease"="true" -P"signing.gnupg.keyName"="${{ secrets.gpgKeyName }}" -P"signing.gnupg.passphrase"="${{ secrets.gpgPassphrase }}"

      - name: Generate docs
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: ./gradlew dokkaHtmlMultiModule

      - name: Deploy docs to Github Pages
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/dokka
          CLEAN: false
          SINGLE_COMMIT: true
