name: update-build-version-catalogs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2.2.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Update Build Version Catalogs
        run: ./gradlew updateBuildVersionCatalogs

      - name: Save Gradle Build Version Catalogs version
        id: build_version_catalogs
        run: echo "::set-output name=version::$(cat build/versions/build-version-catalogs.txt)"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        continue-on-error: true
        with:
          token: ${{ secrets.TOKEN_GITHUB_ACTION  }}
          author: GitHub Action <action@github.com>
          committer: GitHub Action <action@github.com>
          commit-message: "Bump Build Version Catalogs version to ${{ steps.build_version_catalogs.outputs.version }}"
          title: "Bump Build Version Catalogs version to ${{ steps.build_version_catalogs.outputs.version }}"
          body: "Changelog: https://run-blocking-kmp.javiersc.com/CHANGELOG/"
          branch: "bump-build-version-catalogs--${{ steps.build_version_catalogs.outputs.version }}"

      - name: Stop Gradle daemons
        run: ./gradlew --stop
